"""ubah usia ke tanggal_lahir

Revision ID: 0bf2e1c7fcc7
Revises: 36cffae41495
Create Date: 2026-06-02 20:41:16.796304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bf2e1c7fcc7'
down_revision = '36cffae41495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_lahir', sa.Date(), nullable=True))
        batch_op.drop_column('usia')

    with op.batch_alter_table('training_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('training_history_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('Id_User')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Id_User', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('training_history_ibfk_2'), 'users', ['Id_User'], ['Id_User'])

    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usia', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('tanggal_lahir')

    # ### end Alembic commands ###
