"""add artifact_metadata column

Revision ID: f2e1e54d7b8d
Revises: e42de34b02a6
Create Date: 2026-05-05 14:46:47.856525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e1e54d7b8d'
down_revision = 'e42de34b02a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artifact_metadata', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('artifact_metadata')

    # ### end Alembic commands ###
