"""add mood and diary tables

Revision ID: f9ed41f62b50
Revises: f2e1e54d7b8d
Create Date: 2026-05-15 17:42:39.302363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9ed41f62b50'
down_revision = 'f2e1e54d7b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_nim_date'))
        batch_op.drop_constraint(batch_op.f('diary_entries_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'mahasiswa', ['nim'], ['NIM'])

    with op.batch_alter_table('mood_entries', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_nim_date'))
        batch_op.drop_constraint(batch_op.f('mood_entries_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'mahasiswa', ['nim'], ['NIM'])

    with op.batch_alter_table('training_history', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_history', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    with op.batch_alter_table('mood_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mood_entries_ibfk_1'), 'mahasiswa', ['nim'], ['NIM'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_nim_date'), ['nim', 'date'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('diary_entries_ibfk_1'), 'mahasiswa', ['nim'], ['NIM'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_nim_date'), ['nim', 'date'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    op.drop_table('datasets')
    # ### end Alembic commands ###
